version: '3.3'

services:
  db:
    image: postgres
    container_name: go-testing-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "go_testing"